api_test:
  host: '{{.API_HOST}}'
  network_enable: true
  name: subscription_workflow
  global_hook:
    after:
      workflows:
      - step: cleanup_subscription
        request:
          method: DELETE
          uri: /api/merchants/{{.mid}}/subscriptions/{{.subscription_id}}
        expect_response:
          code: SUCCESS
          status_code: 200
  skip: false
  scenarios:
  - skip: false
    name: subscription_workflow
    workflows:
    - step: create_subscribable_entity_plan
      request:
        vars:
        - name: legacy_id
        - name: config_legacy_id
        method: POST
        uri: /api/subscribables_entities
        headers: '{"Content-Type":"application/json"}'
        body: '{"configurations":[{"charges":[{"one_off":true,"price":{"cents":10,"currency_iso":"HKD"},"title":"subscription_fee"}],"duration":1,"duration_unit":"month","is_trial":false,"key":"test_month","legacy_id":"{{.config_legacy_id}}","name_translations":{"en":"test"},"recurring_day":0}],"description_translations":{"en":"test
          plan"},"key":"test_plan","legacy_id":"{{.legacy_id}}","type":"plan"}'
      expect_response:
        code: SUCCESS
        status_code: 200
        body:
          presents:
          - field: data.id
    - step: create_subscription
      request:
        vars:
        - name: mid
        from_response:
        - step: create_subscribable_entity_plan
          name: subscribable_entity_id
          from_field: data.id
        method: POST
        uri: /api/merchants/{{.mid}}/subscriptions
        headers: '{"Content-Type":"application/json"}'
        body: '{"end_at":"{{.next_month}}","start_at":"{{.next_day}}","subscribable_entity_id":"{{.subscribable_entity_id}}"}'
      expect_response:
        code: SUCCESS
        status_code: 200
        body:
          presents:
          - field: data.id
